languageCode = 'zh-cn'
title = 'Devld'
theme = 'paper'

disqusShortname = 'devldd'

[permalinks]
posts = '/:year/:month/:day/:filename/'
page = '/:filename/'

[params]
color = 'light'
rss = true
github = 'devld'

[markup.highlight]
style = 'onedark'
