languageCode = 'zh-cn'
title = 'Devld'
theme = 'paper'

disqusShortname = 'devldd'

[permalinks]
posts = '/:year/:month/:day/:filename/'

[params]
color = 'light'
rss = true

[markup]
[markup.highlight]
lineNos = true
style = 'onedark'
