baseURL = '/'
languageCode = 'zh-cn'
title = 'Devld'
theme = 'paper'

disqusShortname = 'devldd'

[permalinks]
posts = '/:year/:month/:day/:filename/'
page = '/:filename/'

[params]
color = 'light'
rss = true
github = 'devld'
[[params.links]]
name = 'Vgbhfive'
href = 'https://blog.vgbhfive.cn'

[markup.highlight]
style = 'onedark'
