baseURL = 'https://devld.me/'
locale = 'zh-cn'
title = 'Devld'
theme = 'paper'

disqusShortname = 'devldd'

[permalinks]
posts = '/:year/:month/:day/:contentbasename/'
page = '/:contentbasename/'

[params]
color = 'light'
rss = true
github = 'devld'
[[params.links]]
name = 'Vgbhfive'
href = 'https://blog.vgbhfive.cn'

[markup.highlight]
style = 'onedark'

[markup.goldmark.renderer]
unsafe = true
